### ISSUE TITLE
The query SET SQL_BIG_SELECTS=1 isn't supported by postgreSQL

### ISSUE THREAD

**Issue by xillibit** [cobaltcrm/cobalt#101]
The query SET SQL_BIG_SELECTS=1 isn't supported by postgreSQL, but to removing the queries needs to be simplified a bit to work on MySQL without the SET SQL_BIG_SELECTS=1

Is-there a way to fix that ?

**Comment by escopecz** [comment]
Hi, this is good question. We focus firstly to prepare all features of Cobalt to work on MySQL so it will be available for majority of users. Support for other databases will come after that.

**Comment by xillibit** [comment]
I plan to use cobalt but to run on postgreSQL because like that the geographic information system can query in it to get companies list...

**Comment by mbabker** [comment]
For that specific query, you could just wrap it in a `$db->name` check against MySQL.  In general though, the code should be written as database agnostic as possible as that'll make it easier to support other database engines later.

**Comment by xillibit** [comment]
I hadn't thought to do like that to fix it, i will try like that in order to fix

**Comment by Chris-Jones-Gill** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chris.jones-gill@ntlworld.com
    Domain kisswebdesign.co.uk has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:33322 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
    by duffman.enixns.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
    (Exim 4.82)
    (envelope-from noreply@github.com)
    id 1XXCJ7-000ZXT-Qt
    for chris.jones-gill@kisswebdesign.co.uk; Thu, 25 Sep 2014 17:54:17 +0100
Date: Thu, 25 Sep 2014 01:38:42 -0700
