### ISSUE TITLE
Couple of php notices when editing a people

### ISSUE THREAD

**Issue by xillibit** [cobaltcrm/cobalt#119]
When editing a people there are couple of php notices : 

PHP Notice: Undefined index: deals in ...\cobalt_mysql\src\Cobalt\View\People\Html.php:169
PHP Notice: Undefined index: total_pipeline in ...\cobalt_mysql\src\Cobalt\View\People\tmpl\person.php:252
PHP Notice: Undefined index: won_deal_amount in ...\cobalt_mysql\src\Cobalt\View\People\tmpl\person.php:296
PHP Notice: Trying to get property of non-object in ...\cobalt_mysql\src\Cobalt\View\Custom\tmpl\default.php:13
PHP Notice: Undefined variable: company in ...\cobalt_mysql\src\Cobalt\View\People\tmpl\person.php:436

**Comment by xillibit** [comment]
It should be converted into objects instead to have arrays ?

**Comment by escopecz** [comment]
Thanks for report. @juliopontes is working on PHP notices today. There was some code re-factoring lately which caused it

**Comment by xillibit** [comment]
It's ok now
