### ISSUE TITLE
CobaltCRM.org offline - SOLVED

### ISSUE THREAD

**Issue by Duke3D** [cobaltcrm/cobalt#155]
Cloudflare is resolving, but cached copies of the site have all expired.  Returns Error 522

**Comment by dbhurley** [comment]
Thanks! Not sure what it might be. We're looking into it to see what might have happened.

**Comment by dbhurley** [comment]
Alrighty, this was fixed. (Problem with the IP address). Thanks for the assist!

**Comment by Duke3D** [comment]
Site is now requiring credentials (401/htaccess?)  Isn't this intended to be a public-facing site?

**Comment by dbhurley** [comment]
Might be cached, just checked from multiple browsers/locations and have no credential check.

**Comment by Duke3D** [comment]
Your credentials may be cached or Cloudflare may have an interim image.  I'll try later.

**Comment by dbhurley** [comment]
Be sure you are looking at .org and not .com :smile:

Or check here: https://hide.me/en/proxy

Definitely not local problem here. :wink:

**Comment by Duke3D** [comment]
Sorry - switched to Ctrl-Enter when I went to retry - habits!  All good.

**Comment by Duke3D** [comment]
Home page download link https://cobaltcrm.org/cobalt-stable.zip
404 Error

**Comment by dbhurley** [comment]
New ticket :wink: 

That should be pulling from Jenkins and building the package with the dependencies already installed. I'll have to look at our build script.

**Comment by dbhurley** [comment]
http://cobaltcrm.org/downloads/development/cobalt-head.zip

Looks like the path is wrong on the link. I'll have that updated ASAP. Thanks again!
